import '@fortawesome/fontawesome-svg-core/styles.css'
import './globals.css'
import './app.css'

import { Suspense } from 'react'
// import { GeistSans } from 'geist/font/sans'
import { Bangers } from 'next/font/google'

// If loading a variable font, you don't need to specify the font weight
const bangers = Bangers({ display: 'swap', weight: '400', subsets: ['latin'] })
import type { Metadata } from 'next'

// import { AppSidebar } from '@/components/app-sidebar'
// import { Separator } from '@/components/ui/separator'
// import { SidebarInset, SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar'

export const metadata: Metadata = {
	title: 'BlueSky Feed Client',
	// description: "Generated by create next app",
}

type Props = Readonly<{
	children: React.ReactNode
}>

export default function RootLayout({ children }: Props) {
	return (
		<html lang="en" className={`${bangers.className} antialiased bg-green-50`}>
			<body>
				<div className="m-0 h-dvh w-dvw overflow-scroll bg-transparent max-h-svh max-w-full">
					<div className="flex flex-1 flex-col gap-4 p-4 mx-auto overflow-y-scroll h-fit">
						<Suspense fallback={'loading...'}>{children}</Suspense>
					</div>
				</div>
			</body>
		</html>
	)
}
